M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu22.04.1} date 2025-12-30T23:35:00+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-30T23:35:00+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
%
G90
G05
T1
X133.532Y-122.85
X137.532Y-122.85
M30
